blogs/urls.py
from django.conf.urls import patterns, include, url
from blogs import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<blog_id>\d+)/$', views.show, name='show'),
    url(r'^new/$', views.new, name='new'),
    url(r'^create/$', views.create, name='create'),
    url(r'^edit/(?P<blog_id>\d+)/$', views.edit, name='edit'),
    url(r'^update/(?P<blog_id>\d+)/$', views.update, name='update'),
    url(r'^destroy/(?P<blog_id>\d+)/$', views.destroy, name='destroy'),
)

testing/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.contrib.auth import views
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login/$', views.login, {'template_name': 'blogs/login.html'}, name='login'),
    url(r'^signup/$', 'blogs.views.signup', name='signup'),
    url(r'^logout/$', 'blogs.views.logout', name='logout'),
    url(r'^$', RedirectView.as_view(url='/blogs/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blogs/', include('blogs.urls', namespace='blogs')),
)

urlpatterns += staticfiles_urlpatterns()

blogs/models.py
from django.db import models

class Blog(models.Model):
    content = models.TextField()
    writer = models.CharField(max_length=50)
    published_at = models.DateTimeField()
    email = models.EmailField()
    title = models.CharField(max_length=200)
    def __unicode__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(Blog)
    body = models.TextField(max_length=500)
    posted_by = models.EmailField()
    posted_at = models.DateTimeField()

blogs/forms.py
from django.contrib.auth.models import User
from django import forms
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

blogs/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib import auth

from blogs.forms import UserForm
from blogs.models import Blog

def index(request):
    if request.user.is_authenticated() == False:
        return HttpResponseRedirect(reverse('login'))
    blog_list = Blog.objects.order_by('-published_at')
    return render(request, 'blogs/index.html', {'blog_list': blog_list,})

def show(request, blog_id):
    if request.user.is_authenticated() == False:
        return HttpResponseRedirect(reverse('login'))
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blogs/show.html', {'blog': blog,})

def new(request):
    if request.user.is_authenticated() == False:
        return HttpResponseRedirect(reverse('login'))
    return render(request, 'blogs/new.html', {})

def create(request):
    if request.user.is_authenticated() == False:
        return HttpResponseRedirect(reverse('login'))
    b = Blog(title=request.POST['blog[title]'],
             content=request.POST['blog[content]'],
             writer=request.POST['blog[writer]'],
             published_at=timezone.now(),
             email=request.POST['blog[email]'])
    b.save()
    return HttpResponseRedirect(reverse('blogs:show', args=(b.id,)))

def edit(request, blog_id):
    if request.user.is_authenticated() == False:
        return HttpResponseRedirect(reverse('login'))
    blog = Blog.objects.get(pk=blog_id)
    return render(request, 'blogs/edit.html', {'blog': blog})

def update(request, blog_id):
    if request.user.is_authenticated() == False:
        return HttpResponseRedirect(reverse('login'))
    b = get_object_or_404(Blog, pk=blog_id)
    b.title = request.POST['blog[title]']
    b.content = request.POST['blog[content]']
    b.writer = request.POST['blog[writer]']
    b.email = request.POST['blog[email]']
    b.save()
    return HttpResponseRedirect(reverse('blogs:show', args=(b.id,)))

def destroy(request, blog_id):
    if request.user.is_authenticated() == False:
        return HttpResponseRedirect(reverse('login'))
    b = get_object_or_404(Blog, pk=blog_id)
    b.delete()
    return HttpResponseRedirect(reverse('blogs:index'))


def logout(request):
    if request.user.is_authenticated() == False:
        return HttpResponseRedirect(reverse('login'))
    auth.logout(request)
    return HttpResponseRedirect(reverse('login'))

def signup(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('blogs:index'))
    registered = False
    user_form = UserForm(data=request.POST)
    if user_form.is_valid():
        user = user_form.save()
        user.set_password(user.password)
        user.save()
        registered = True
    else:
        print user_form.errors
    return render(
            request,
            'blogs/signup.html',
            {'user_form': user_form, 'registered': registered})

blogs/templates/blogs/edit.html
{% extends "blogs/layout.html" %}
{% block title %}Edit blog post{% endblock %}
{% block content %}
<h1>{{ blog.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'blogs:update' blog.id %}" method="post">
{% csrf_token %}
    Title:
    <input type="text" name="blog[title]" id="title" value="{{ blog.title }}"/>
    Content:
    <textarea id="content" name="blog[content]">{{ blog.content }}</textarea>
    Writer:
    <input type="text" name="blog[writer]" id="writer" value="{{ blog.writer }}"/>
    Email:
    <input type="text" name="blog[email]" id="email" value="{{ blog.email }}"/>
    Published at:
    {{ blog.published_at }}
<input type="submit" value="Update" />
</form>
<br />
<a href="/blogs">Home</a>
{% endblock %}

blogs/templates/blogs/index.html
{% extends "blogs/layout.html" %}
{% block title %}All posts{% endblock %}
{% block content %}
{% if blog_list %}
<table>
    <tr>
        <th>Title</th>
        <th>Writer</th>
        <th>Email</th>
        <th>Date published</th>
        <th> </th>
        <th> </th>
    </tr>
    {% for blog in blog_list %}
    <tr>
        <td><a href="{% url 'blogs:show' blog.id %}" class="customLink">{{ blog.title }}</a></td>
        <td>{{ blog.writer }}</td>
        <td>{{ blog.email }}</td>
        <td>{{ blog.published_at }}</td>
        <td><a href="{% url 'blogs:edit' blog.id%} " class="customLink">Edit</a></td>
        <td><a href="{% url 'blogs:destroy' blog.id%}" onclick="javascript:return(confirm('Are you sure?'))" class="customLink">Delete</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
    <p>No blog posts are available.</p>
{% endif %}
<a href="/logout" onclick="javascript:return(confirm('Are you sure?'))" class="createNewPost">Logout!</a>
<br /><br />
<a href="/blogs/new" class="createNewPost">Create new post</a>
<br /><br />
<div class="clear"> </div>
{% endblock %}

blogs/templates/blogs/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>My Blog | {% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
<div id="header">
	<div class="container">
		My Blog Header
	</div>
</div>
<div id="content">
	<div class="container">
		{% block content %}{% endblock %}
	</div>
</div>
<div id="footer">
	<div class="container">
		My Blog Footer
	</div>
</div>
</body>
</html>

blogs/templates/blogs/login.html
{% extends "blogs/layout.html" %}
{% block title %}Login{% endblock %}
{% block content %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="/blogs" />
</form>
<a href="{% url 'signup' %}">Signup here</a>
{% endblock %}

blogs/templates/blogs/new.html
{% extends "blogs/layout.html" %}
{% block title %}New Post{% endblock %}
{% block content %}
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'blogs:create' %}" method="post">
{% csrf_token %}
    Title:
    <input type="text" name="blog[title]" id="title" />
    Content:
    <textarea id="content" name="blog[content]"></textarea>
    Writer:
    <input type="text" name="blog[writer]" id="writer" />
    Email:
    <input type="text" name="blog[email]" id="email" />
<input type="submit" value="Create" />
</form>
<br />
<a href="/blogs">Home</a>
{% endblock %}

blogs/templates/blogs/show.html
{% extends "blogs/layout.html" %}
{% block title %}{{ blog.title }}{% endblock %}
{% block content %}
<h1>
    {{ blog.title }}
</h1>
<p>
    {{ blog.content }}
</p>
<p>
    Posted at: {{ blog.published_at }}
</p>
<p>
    Posted by: {{ blog.writer }} <br/>
    Email: {{ blog.email }}
</p>
<br />
<a href="/blogs">Home</a>
{% endblock %}

blogs/templates/blogs/signup.html
{% extends "blogs/layout.html" %}
{% block title %}Register{% endblock %}
{% block content %}
{% if registered %}
<strong>Thank you for registering!</strong>
<a href="/">Return to the homepage.</a><br />
{% else %}
<strong>Register here!</strong><br />
<form id="user_form" method="post" action="/signup/">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}